clear all
% Reaching Task Master Script
gpath = 'C:\Users\Tim\Documents\Work\GIT';
% Setup Images
baseTar = {
    [gpath '\reaching_task\task_images\targets\fixation_cross_targets.bmp'];...
    [gpath '\reaching_task\task_images\targets\0_0_0_0_targets.bmp'];...
    };

selTar(:,1) ={
    [gpath '\reaching_task\task_imagesCR\black_squares\1_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_4_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_1_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_2_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_4_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_1_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_2_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_4_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_1_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_2_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_3_target_b.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_4_target_b.png'];...
    };

selTar(:,2) = {
    [gpath '\reaching_task\task_imagesCR\black_squares\1_1_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_2_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_3_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\1_4_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_1_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_2_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_3_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\2_4_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_1_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_2_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_3_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\3_4_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_1_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_2_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_3_target_a.png'];...
    [gpath '\reaching_task\task_imagesCR\black_squares\4_4_target_a.png'];...
    };


% Setup Display
% config_display(0, 6, [0 0 0], [0 1 0], 'Helvetica', 50, 16);
config_display(0,6, [1 1 1],[0 0 0],'Helvetica', 50);
config_log( 'reachingTask.log' ); % Configure log file
start_cogent;

txt_welcomeStr = 'Get ready!';
preparestring( txt_welcomeStr, 2 ); % Put word in buffer 1
% Draw Welcome Text
t0 = drawpict( 2 );
waituntil( t0 + 2000 );
for sz=1:size(selTar,2)
    % Fixation cross
    clearpict( 1 );
    loadpict( baseTar{1}, 1 );
    
    % Setup rng seed (so to make reproducible sequence)
    rng(14231)
    % Setup number of trials
    ntrials = 5;
    % Setup random vector of targets
    tarlist = randi(16,1,ntrials);
    
    % Fixation Cross
    t(1) = drawpict( 1 ); % Display fixation cross
    waituntil( t(1) + 5000 ); % Display fixation point for 1000ms
    
    % Fixation Cross
    t(1) = drawpict( 1 ); % Display fixation cross
    waituntil( t(1) + 5000 ); % Display fixation point for 1000ms
    for i = 1:ntrials
        % Target Range
        t(2) = drawpict( 3 ); % Display target range
        r = randn(2500,1000,1);
        waituntil( t(2)+ r);
        clearpict( 4 );
        loadpict( selTar{tarlist(i),sz}, 4 );
        t(3) = drawpict( 4 ); % Display word and get the time
        waituntil(t(3)+ 1000 );
    end
end

clearpict( 1 );
clearpict( 4 );
txt_restStr = 'Have a rest';
preparestring( txt_restStr, 1); % Put word in buffer 1
% Draw Welcome Text
t(4) = drawpict( 1 );
waituntil( t(4) + 5000 );
stop_cogent;