function configuration(path, tracking, labjack, tick, pointervisible, reaches, condinfo, breakreaches, breakwait, posturalhold, rest, posturestart, reachwait, prepwait, delaywait, holdwait, colorduration)
% function configuration(confpath, labjack, tick, pointervisible, reaches, arrows, condinfo, posturalhold, rest, posturestart, reachwait, prepwait, delaywait, holdwait, colorduration, balloonsize)

fileTRACKING = fopen([path '\TRACKING.txt'],'w');
fprintf(fileTRACKING,tracking);
fclose(fileTRACKING);
fileLABJACK = fopen([path '\LABJACK.txt'],'w');
fprintf(fileLABJACK,labjack);
fclose(fileLABJACK);
fileTICK = fopen([path '\TICK.txt'],'w');
fprintf(fileTICK,tick);
fclose(fileTICK);
fileVISIBLE = fopen([path '\VISIBLE.txt'],'w');
fprintf(fileVISIBLE,pointervisible);
fclose(fileVISIBLE);
fileREACHES = fopen([path '\REACHES.txt'],'w');
fprintf(fileREACHES,reaches);
fclose(fileREACHES);
% fileUNCERTAINTY = fopen([path '\UNCERTAINTY.txt'],'w');
% fprintf(fileUNCERTAINTY,uncertainty);
% fclose(fileUNCERTAINTY);
fileCONDINFO = fopen([path '\CONDINFO.txt'],'w');
fprintf(fileCONDINFO,condinfo);
fclose(fileCONDINFO);
fileBREAKREACHES = fopen([path '\BREAKREACHES.txt'],'w');
fprintf(fileBREAKREACHES,breakreaches);
fclose(fileBREAKREACHES);
fileBREAKWAIT = fopen([path '\BREAKWAIT.txt'],'w');
fprintf(fileBREAKWAIT,breakwait);
fclose(fileBREAKWAIT);
filePOSTHOLD = fopen([path '\POSTHOLD.txt'],'w');
fprintf(filePOSTHOLD,posturalhold);
fclose(filePOSTHOLD);
fileREST = fopen([path '\REST.txt'],'w');
fprintf(fileREST,rest);
fclose(fileREST);
filePOSTSTART = fopen([path '\POSTSTART.txt'],'w');
fprintf(filePOSTSTART,posturestart);
fclose(filePOSTSTART);
fileREACHWAIT = fopen([path '\REACHWAIT.txt'],'w');
fprintf(fileREACHWAIT,reachwait);
fclose(fileREACHWAIT);
filePREPWAIT = fopen([path '\PREPWAIT.txt'],'w');
fprintf(filePREPWAIT,prepwait);
fclose(filePREPWAIT);
fileDELAYWAIT = fopen([path '\DELAYWAIT.txt'],'w');
fprintf(fileDELAYWAIT,delaywait);
fclose(fileDELAYWAIT);
fileHOLDWAIT = fopen([path '\HOLDWAIT.txt'],'w');
fprintf(fileHOLDWAIT,holdwait);
fclose(fileHOLDWAIT);
fileCOLORDUR = fopen([path '\COLORDURATION.txt'],'w');
fprintf(fileCOLORDUR,colorduration);
fclose(fileCOLORDUR);
% fileBALLOONSIZE = fopen([path '\BALLOONSIZE.txt'],'w');
% fprintf(fileBALLOONSIZE,balloonsize);
% fclose(fileBALLOONSIZE);